# Generated by Django 5.1.3 on 2024-11-17 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='resources/')),
                ('category', models.CharField(choices=[('MATH', 'Math'), ('PHYSICS', 'Physics')], max_length=10)),
                ('grade', models.CharField(blank=True, choices=[('GRADE_11', 'Grade 11'), ('GRADE_12', 'Grade 12'), ('CALCULUS', 'Calculus'), ('LINEAR_ALGEBRA', 'Linear Algebra')], max_length=20, null=True)),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
