# Generated by Django 5.1.3 on 2024-11-24 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='is_video',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resource',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='category',
            field=models.CharField(choices=[('MATH', 'Math'), ('PHYSICS', 'Physics')], max_length=100),
        ),
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='grade',
            field=models.CharField(blank=True, choices=[('GRADE_11', 'Grade 11'), ('GRADE_12', 'Grade 12'), ('CALCULUS', 'Calculus'), ('LINEAR_ALGEBRA', 'Linear Algebra')], max_length=100, null=True),
        ),
    ]
